<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AssemblyName>TargetPortal</AssemblyName>
    <RootNamespace>TargetPortal</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GamePath>D:\Program Files\Steam\steamapps\common\Valheim</GamePath>
    <BepInExPath>C:\Users\User\AppData\Roaming\Thunderstore Mod Manager\DataFolder\Valheim\profiles\Valheim Moded\BepInEx</BepInExPath>
    <PublicizedPath>C:\Users\User\Projects\Valheim10Patches\libs\publicized</PublicizedPath>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.18.2" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(BepInExPath)\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>$(BepInExPath)\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="assembly_valheim">
      <HintPath>$(PublicizedPath)\assembly_valheim_publicized.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="assembly_utils">
      <HintPath>$(PublicizedPath)\assembly_utils_publicized.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="assembly_guiutils">
      <HintPath>$(PublicizedPath)\assembly_guiutils_publicized.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Splatform">
      <HintPath>$(PublicizedPath)\Splatform_publicized.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>$(GamePath)\valheim_Data\Managed\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(GamePath)\valheim_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(GamePath)\valheim_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(GamePath)\valheim_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(GamePath)\valheim_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(GamePath)\valheim_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(GamePath)\valheim_Data\Managed\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(GamePath)\valheim_Data\Managed\Unity.TextMeshPro.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Groups">
      <HintPath>GroupsAPI.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Guilds">
      <HintPath>GuildsAPI.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="ServerSync">
      <HintPath>ServerSync.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="portalicon.png" />
    <None Include="ILRepack.targets" />
  </ItemGroup>
</Project>